const nodeGlobals = Object.fromEntries([
  'AbortController',
  'Buffer',
  'URL',
  'clearTimeout',
  'console',
  'process',
  'setTimeout',
  'structuredClone',
].map(name => [name, 'readonly']));

export default [{
  files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
  ignores: ['.agents/**', '.claude/skills/**', '.code-review-graph/**', '.ctxroute/**', 'coverage/**', 'dist/**', 'node_modules/**', 'packages/code-review-graph/.venv/**'],
  languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: nodeGlobals },
  linterOptions: { reportUnusedDisableDirectives: 'error' },
  rules: {
    'complexity': ['error', 120],
    'max-depth': ['error', 8],
    'max-lines-per-function': ['error', { max: 200, skipBlankLines: true, skipComments: true }],
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': ['error', 'except-parens'],
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-obj-calls': 'error',
    'no-promise-executor-return': 'error',
    'no-prototype-builtins': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-unused-vars': ['error', { args: 'after-used', argsIgnorePattern: '^_', caughtErrors: 'none' }],
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error'
  },
}];
