import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, utimesSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LIMITS, emptyProgress, ensureProgressView, readProgress, validateProgress, validatePlan, approvePlan, progressStatus, progressNext, claimProgressTicket, claimAutomaticProgressTicket, releaseProgressClaims, updateProgressGoal, updateProgressStep, addProgressStep, deleteProgressStep, reorderProgressSteps, setProgressMode, markModeOffered, progressRevision, renderProgress, renameWithRetry } from '../scripts/progress-core.mjs';
import { hasAutonomousOffer, hasNextStepHandoff, isExternallyBlocked, isFullyBlocked, selectProgressGoal } from '../scripts/progress-handoff.mjs';

const plan = (overrides = {}) => ({ goalId: 'goal-9', title: 'Checklist', validationEvidence: ['tests/progress-core.test.mjs'], steps: [{ id: 'step-1', title: 'Define contract', acceptance: ['Schema validated'], files: ['.project/progress.json'], commands: ['npm test'], evidence: [] }], ...overrides });
const root = () => mkdtempSync(join(tmpdir(), 'progress-'));
const repositoryRoot = fileURLToPath(new URL('..', import.meta.url));

test('empty checklist is read-only and has stable shape', async () => { const directory = root(); assert.deepEqual(await readProgress(directory), emptyProgress()); assert.equal(existsSync(join(directory, '.project/progress.json')), false); });
test('tracked progress is valid and its generated view stays synchronized', async () => {
  const progress = await readProgress(repositoryRoot);
  assert.deepEqual(validateProgress(progress), []);
  assert.equal(readFileSync(join(repositoryRoot, 'docs/progress.md'), 'utf8'), renderProgress(progress));
  assert.deepEqual(readdirSync(join(repositoryRoot, '.project')).filter(name => name.endsWith('-plan.json')), []);
});
test('validate-plan requires intent and evidence but keeps files and commands optional', async () => { const directory = root(); const result = validatePlan({ goalId: 'goal-9', title: 'Bad', steps: [{ id: 'step-1', title: 'Bad' }] }, await readProgress(directory)); assert.equal(result.ok, false); assert.equal(existsSync(join(directory, '.project/progress.json')), false); assert.ok(result.errors.length >= 2); assert.equal(validatePlan({ goalId: 'lean', title: 'Lean memory', validationEvidence: ['review'], steps: [{ id: 'outcome', title: 'Deliver outcome', acceptance: ['Outcome verified'] }] }).ok, true); });
test('approval writes JSON and generated Markdown atomically and is idempotent', async () => { const directory = root(); const first = await approvePlan({ ...plan(), approved: true }, directory); const json = readFileSync(join(directory, '.project/progress.json'), 'utf8'); const markdown = readFileSync(join(directory, 'docs/progress.md'), 'utf8'); assert.deepEqual(JSON.parse(json), first); assert.match(markdown, /Checklist — ACTIVE/u); const second = await approvePlan({ ...plan(), approved: true }, directory); assert.deepEqual(second, first); });
test('legacy plans without claimable remain idempotent', async () => { const directory = root(); const legacy = { schemaVersion: 1, goals: [{ schemaVersion: 1, id: 'goal-9', title: 'Checklist', status: 'ACTIVE', executionMode: 'automatic', manualReason: null, modeOffered: false, steps: plan().steps.map(step => ({ ...step, status: 'TODO' })) }] }; mkdirSync(join(directory, '.project')); writeFileSync(join(directory, '.project/progress.json'), JSON.stringify(legacy)); const result = await approvePlan({ ...plan(), approved: true }, directory); assert.equal(result.goals[0].steps[0].claimable, undefined); });
test('multiple goals preserve insertion order and status is compact', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await approvePlan({ ...plan({ goalId: 'goal-10', title: 'Second' }), approved: true }, directory); const status = progressStatus(await readProgress(directory)); assert.deepEqual(status.map(item => item.id), ['goal-9', 'goal-10']); assert.deepEqual(status[0].steps, { total: 1, todo: 1, inProgress: 0, blocked: 0, done: 0 }); });
test('materialization requires its write flag and rejects invalid plans', async () => { const directory = root(); await assert.rejects(() => approvePlan(plan(), directory), /write flag/u); assert.equal(validatePlan({ ...plan(), executionMode: 'sometimes' }).ok, false); assert.equal(validatePlan({ ...plan(), steps: [{ ...plan().steps[0], files: ['../secret'] }], validationEvidence: ['ok'] }).ok, false); assert.equal(validatePlan({ ...plan(), steps: [{ ...plan().steps[0], id: 'step-1' }, { ...plan().steps[0], id: 'step-1' }] }).ok, false); assert.equal(validatePlan({ ...plan(), validationEvidence: ['apiKey: hidden'] }).ok, false); });
test('invalid stored JSON is rejected', async () => { const directory = root(); const path = join(directory, '.project/progress.json'); mkdirSync(join(directory, '.project')); writeFileSync(path, '{invalid'); await assert.rejects(() => readProgress(directory), /Cannot read progress checklist/u); });
test('stored progress accepts current and legacy execution modes and rejects unknown modes', () => { const value = { schemaVersion: 1, goals: [{ id: 'goal-9', title: 'Modes', status: 'ACTIVE', executionMode: 'automatic', modeOffered: true, steps: [{ id: 'step-1', title: 'Verify', status: 'TODO', acceptance: ['ok'], files: ['.project/progress.json'], commands: ['npm test'], evidence: [] }] }] }; for (const executionMode of ['automatic', 'manual', 'autonomous', 'collaborative']) { const manualReason = ['manual', 'collaborative'].includes(executionMode) ? 'visual-review' : null; assert.deepEqual(validateProgress({ ...value, goals: [{ ...value.goals[0], executionMode, manualReason }] }), []); } assert.match(validateProgress({ ...value, goals: [{ ...value.goals[0], executionMode: 'paused' }] })[0], /executionMode/u); });
test('stored progress validation rejects duplicate goal identifiers', () => { const goal = { id: 'goal-9', title: 'Goal', status: 'ACTIVE', steps: [] }; assert.match(validateProgress({ schemaVersion: 1, goals: [goal, goal] }).join(' '), /goal ids/u); });
test('stored progress validation rejects malformed step references', () => { const goal = { id: 'goal-9', title: 'Goal', status: 'ACTIVE', steps: [{ id: 'step-1', title: 'Step', status: 'TODO', acceptance: ['ok'], files: ['../outside'], commands: ['npm test'], evidence: [] }] }; assert.match(validateProgress({ schemaVersion: 1, goals: [goal] }).join(' '), /invalid files/u); });
test('stored progress validation bounds evidence references', () => { const evidence = Array.from({ length: LIMITS.evidence + 1 }, (_, index) => `proof-${index}`); const goal = { id: 'goal-9', title: 'Goal', status: 'ACTIVE', steps: [{ id: 'step-1', title: 'Step', status: 'DONE', acceptance: ['ok'], files: ['src/app.js'], commands: ['npm test'], evidence }] }; assert.match(validateProgress({ schemaVersion: 1, goals: [goal] }).join(' '), /too many evidence/u); });
test('stored progress validation requires the versioned root shape', () => { assert.deepEqual(validateProgress({ schemaVersion: 2, goals: [] }), ['schemaVersion 1 and goals array are required']); });
test('stored progress validation accepts an empty versioned checklist', () => { assert.deepEqual(validateProgress(emptyProgress()), []); });
test('stored progress validation bounds the number of goals', () => { const goals = Array.from({ length: LIMITS.goals + 1 }, (_, index) => ({ id: `goal-${index}`, title: `Goal ${index}`, status: 'ACTIVE', steps: [] })); assert.match(validateProgress({ schemaVersion: 1, goals }).join(' '), /maximum/u); });
test('goals without a mode default to automatic', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); const value = await readProgress(directory); delete value.goals[0].executionMode; delete value.goals[0].modeOffered; writeFileSync(join(directory, '.project/progress.json'), JSON.stringify(value)); assert.equal(progressStatus(await readProgress(directory))[0].executionMode, 'automatic'); });
test('manual mode requires and persists a classified reason', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await assert.rejects(() => setProgressMode('goal-9', 'manual', true, directory), /requires/u); for (const reason of ['visual-review', 'important-decision']) { const changed = await setProgressMode('goal-9', 'manual', reason, directory); assert.equal(changed.goals[0].manualReason, reason); assert.equal(progressStatus(changed)[0].manualReason, reason); } const automatic = await setProgressMode('goal-9', 'automatic', undefined, directory); assert.equal(automatic.goals[0].manualReason, null); assert.equal(Object.hasOwn(progressStatus(automatic)[0], 'manualReason'), false); });
test('new manual plans require a reason while completed legacy manual goals normalize to unknown', async () => { assert.equal(validatePlan({ ...plan(), executionMode: 'manual' }).ok, false); assert.equal(validatePlan({ ...plan(), executionMode: 'manual', manualReason: 'visual-review' }).ok, true); const directory = root(); const legacy = { schemaVersion: 1, goals: [{ id: 'legacy', title: 'Legacy', status: 'DONE', executionMode: 'manual', steps: [{ id: 'done', title: 'Done', status: 'DONE', acceptance: ['ok'], files: [], commands: [], evidence: ['proof'] }] }] }; mkdirSync(join(directory, '.project')); writeFileSync(join(directory, '.project/progress.json'), JSON.stringify(legacy)); const read = await readProgress(directory); assert.equal(read.goals[0].manualReason, null); assert.equal(progressStatus(read)[0].manualReason, null); });
test('mode offer persistence marks the active goal once', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await markModeOffered('goal-9', directory); assert.equal((await readProgress(directory)).goals[0].modeOffered, true); });
test('mode offer persistence rejects unknown goals', async () => { await assert.rejects(() => markModeOffered('missing', root()), /Unknown goal/u); });
test('mode offer persistence is idempotent', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await markModeOffered('goal-9', directory); const first = await readProgress(directory); await markModeOffered('goal-9', directory); assert.deepEqual(await readProgress(directory), first); });
test('parallel agents atomically claim distinct tickets', async () => { const directory = root(); const steps = Array.from({ length: 4 }, (_, index) => ({ ...plan().steps[0], id: `step-${index + 1}`, title: `Ticket ${index + 1}` })); await approvePlan({ ...plan({ steps }), approved: true }, directory); const claims = await Promise.all(['agent-a', 'agent-b', 'agent-c', 'agent-d'].map(agentId => claimProgressTicket(agentId, 'goal-9', directory))); assert.equal(new Set(claims.map(claim => claim.ticket.stepId)).size, 4); assert.equal((await readProgress(directory)).goals[0].steps.filter(step => step.status === 'IN_PROGRESS').length, 4); });
test('separate agent processes atomically claim distinct tickets', async () => { const directory = root(); const steps = Array.from({ length: 4 }, (_, index) => ({ ...plan().steps[0], id: `step-${index + 1}`, title: `Ticket ${index + 1}` })); await approvePlan({ ...plan({ steps }), approved: true }, directory); const script = join(repositoryRoot, 'scripts/progress-cli.mjs'); const claims = await Promise.all(['agent-a', 'agent-b', 'agent-c', 'agent-d'].map(agentId => execute(process.execPath, [script, 'claim', agentId, 'goal-9'], directory))); assert.equal(new Set(claims.map(output => JSON.parse(output).ticket.stepId)).size, 4); });
test('atomic replacement retries transient Windows file locks', async () => { let attempts = 0; await renameWithRetry('from', 'to', { waitMs: 100, wait: async () => {}, operation: async () => { attempts += 1; if (attempts < 3) { const error = new Error('busy'); error.code = 'EPERM'; throw error; } } }); assert.equal(attempts, 3); });
test('the maximum burst of thirty agent processes claims every ticket exactly once', async () => { const directory = root(); const steps = Array.from({ length: LIMITS.steps }, (_, index) => ({ ...plan().steps[0], id: `step-${index + 1}`, title: `Ticket ${index + 1}` })); await approvePlan({ ...plan({ steps }), approved: true }, directory); const script = join(repositoryRoot, 'scripts/progress-cli.mjs'); const claims = await Promise.all(steps.map((_, index) => execute(process.execPath, [script, 'claim', `agent-${index + 1}`, 'goal-9'], directory))); const stepIds = claims.map(output => JSON.parse(output).ticket.stepId); assert.equal(new Set(stepIds).size, steps.length); assert.equal((await readProgress(directory)).goals[0].steps.filter(step => step.status === 'IN_PROGRESS').length, steps.length); });
test('claim is idempotent and final reporting respects ticket ownership', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); const first = await claimProgressTicket('agent-a', 'goal-9', directory); const repeated = await claimProgressTicket('agent-a', 'goal-9', directory); assert.deepEqual(repeated, first); await assert.rejects(() => updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', agentId: 'agent-b', status: 'DONE', evidence: ['npm test'] }, directory), /assigned to agent-a/u); await updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', agentId: 'agent-a', status: 'DONE', evidence: ['npm test'] }, directory); assert.equal((await claimProgressTicket('agent-b', 'goal-9', directory)).claimed, false); });
test('automatic claims skip manual and non-claimable memory milestones', async () => { const directory = root(); await approvePlan({ ...plan({ executionMode: 'manual', manualReason: 'visual-review', steps: [{ ...plan().steps[0], claimable: true }] }), approved: true }, directory); await approvePlan({ ...plan({ goalId: 'memory', title: 'Memory only' }), approved: true }, directory); await approvePlan({ ...plan({ goalId: 'automatic', title: 'Automatic', steps: [{ ...plan().steps[0], claimable: true }] }), approved: true }, directory); const first = await claimAutomaticProgressTicket('harness:session:agent', directory); const repeated = await claimAutomaticProgressTicket('harness:session:agent', directory); assert.equal(first.ticket.goalId, 'automatic'); assert.deepEqual(repeated, first); assert.equal((await readProgress(directory)).goals.find(goal => goal.id === 'memory').steps[0].status, 'TODO'); });
test('session claim release is atomic, scoped, and idempotent', async () => { const directory = root(); const steps = Array.from({ length: 3 }, (_, index) => ({ ...plan().steps[0], id: `step-${index + 1}`, claimable: true })); await approvePlan({ ...plan({ steps }), approved: true }, directory); await claimAutomaticProgressTicket('codex:session-a:agent-a', directory); await claimAutomaticProgressTicket('codex:session-a:agent-b', directory); await claimAutomaticProgressTicket('codex:session-b:agent-a', directory); const first = await releaseProgressClaims('codex:session-a:', directory); assert.equal(first.released, 2); assert.equal((await readProgress(directory)).goals[0].steps.filter(step => step.status === 'IN_PROGRESS').length, 1); assert.equal((await releaseProgressClaims('codex:session-a:', directory)).released, 0); });
test('agent reporting rejects an unclaimed ticket', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await assert.rejects(() => updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', agentId: 'agent-a', status: 'DONE', evidence: ['npm test'] }, directory), /must be claimed/u); });
test('a dead stale lock is recovered under a serialized recovery guard', async () => { const directory = root(); const state = join(directory, '.ctxroute/state'); mkdirSync(state, { recursive: true }); const lock = join(state, 'progress.lock'); writeFileSync(lock, JSON.stringify({ pid: 2_147_483_647, token: 'dead' })); const old = new Date(Date.now() - 31_000); utimesSync(lock, old, old); await approvePlan({ ...plan(), approved: true }, directory); assert.equal((await readProgress(directory)).goals[0].id, 'goal-9'); assert.equal(existsSync(lock), false); assert.equal(existsSync(`${lock}.recovery`), false); });
test('a stale lock without an ownership token is preserved', async () => { const directory = root(); const state = join(directory, '.ctxroute/state'); mkdirSync(state, { recursive: true }); const lock = join(state, 'progress.lock'); writeFileSync(lock, JSON.stringify({ pid: 2_147_483_647 })); const old = new Date(Date.now() - 31_000); utimesSync(lock, old, old); await assert.rejects(() => approvePlan({ ...plan(), approved: true }, directory), error => error.code === 'PROGRESS_BUSY'); assert.equal(existsSync(lock), true); });
test('a dead stale recovery marker is reclaimed with token ownership', async () => { const directory = root(); const state = join(directory, '.ctxroute/state'); mkdirSync(state, { recursive: true }); const lock = join(state, 'progress.lock'); const recovery = `${lock}.recovery`; writeFileSync(lock, JSON.stringify({ pid: 2_147_483_647, token: 'dead-lock' })); writeFileSync(recovery, JSON.stringify({ pid: 2_147_483_647, token: 'dead-recovery' })); const old = new Date(Date.now() - 31_000); utimesSync(lock, old, old); utimesSync(recovery, old, old); await approvePlan({ ...plan(), approved: true }, directory); assert.equal(existsSync(lock), false); assert.equal(existsSync(recovery), false); });
test('recent or live recovery markers and live progress locks are preserved', async () => { for (const owner of [{ target: 'progress.lock', pid: process.pid, stale: true }, { target: 'progress.lock.recovery', pid: 2_147_483_647, stale: false }, { target: 'progress.lock.recovery', pid: process.pid, stale: true }]) { const directory = root(); const state = join(directory, '.ctxroute/state'); mkdirSync(state, { recursive: true }); const lock = join(state, 'progress.lock'); writeFileSync(lock, JSON.stringify({ pid: 2_147_483_647, token: 'blocked-primary' })); const old = new Date(Date.now() - 31_000); utimesSync(lock, old, old); if (owner.target.endsWith('.recovery')) { writeFileSync(`${lock}.recovery`, JSON.stringify({ pid: owner.pid, token: 'preserved-recovery' })); if (owner.stale) utimesSync(`${lock}.recovery`, old, old); } else { writeFileSync(lock, JSON.stringify({ pid: owner.pid, token: 'preserved-primary' })); utimesSync(lock, old, old); } await assert.rejects(() => approvePlan({ ...plan(), approved: true }, directory), error => error.code === 'PROGRESS_BUSY'); assert.equal(existsSync(join(state, owner.target)), true); } });
test('a stale or missing Markdown view is repaired from JSON', async () => { const directory = root(); const current = await approvePlan({ ...plan(), approved: true }, directory); const changed = { ...current, goals: current.goals.map(goal => ({ ...goal, title: 'Recovered after crash' })) }; writeFileSync(join(directory, '.project/progress.json'), `${JSON.stringify(changed, null, 2)}\n`); writeFileSync(join(directory, 'docs/progress.md'), '# stale\n'); await ensureProgressView(directory); const view = readFileSync(join(directory, 'docs/progress.md'), 'utf8'); assert.equal(view, renderProgress(changed)); assert.match(view, new RegExp(progressRevision(changed), 'u')); });
test('CLI startup repairs the generated view after a JSON-only write', async () => { const directory = root(); const current = await approvePlan({ ...plan(), approved: true }, directory); writeFileSync(join(directory, 'docs/progress.md'), '# interrupted write\n'); await execute(process.execPath, [join(repositoryRoot, 'scripts/progress-cli.mjs'), 'status'], directory); assert.equal(readFileSync(join(directory, 'docs/progress.md'), 'utf8'), renderProgress(current)); });
test('step updates are bounded, idempotent, and recalculate goal status', async () => { const directory = root(); const two = { ...plan(), steps: [{ ...plan().steps[0], id: 'step-1' }, { ...plan().steps[0], id: 'step-2', title: 'Verify' }] }; await approvePlan({ ...two, approved: true }, directory); await assert.rejects(() => updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', status: 'DONE' }, directory), /evidence/u); const update = { goalId: 'goal-9', stepId: 'step-1', status: 'DONE', evidence: ['npm test'] }; await updateProgressStep(update, directory); await updateProgressStep(update, directory); assert.equal((await readProgress(directory)).goals[0].status, 'ACTIVE'); await updateProgressStep({ goalId: 'goal-9', stepId: 'step-2', status: 'BLOCKED' }, directory); assert.equal((await readProgress(directory)).goals[0].status, 'BLOCKED'); });
test('goal and every editable step field update atomically without changing ids', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); const current = await readProgress(directory); await updateProgressGoal('goal-9', { title: 'Renamed goal' }, directory, { expectedRevision: progressRevision(current) }); await updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', title: 'Renamed step', claimable: true, acceptance: ['Ready'], files: ['scripts/progress-core.mjs'], commands: ['node --test'], evidence: ['checked'] }, directory); const changed = await readProgress(directory); assert.equal(changed.goals[0].id, 'goal-9'); assert.equal(changed.goals[0].title, 'Renamed goal'); assert.deepEqual(changed.goals[0].steps[0], { id: 'step-1', title: 'Renamed step', status: 'TODO', claimable: true, acceptance: ['Ready'], files: ['scripts/progress-core.mjs'], commands: ['node --test'], evidence: ['checked'] }); assert.match(readFileSync(join(directory, 'docs/progress.md'), 'utf8'), /Renamed goal/u); });
test('step field updates retain omitted fields and reject unsafe or unbounded values', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', status: 'IN_PROGRESS' }, directory); assert.deepEqual((await readProgress(directory)).goals[0].steps[0].acceptance, ['Schema validated']); await assert.rejects(() => updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', files: ['../outside'] }, directory), /invalid files/u); await assert.rejects(() => updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', acceptance: Array(LIMITS.references + 1).fill('item') }, directory), /bounded acceptance/u); });
test('steps can be added, exactly reordered, and deleted with derived statuses', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await addProgressStep('goal-9', { id: 'step-2', title: 'Second', claimable: true, acceptance: ['ok'], files: ['src/app.js'], commands: ['npm test'] }, directory); assert.equal((await readProgress(directory)).goals[0].steps[1].claimable, true); await updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', status: 'BLOCKED' }, directory); await updateProgressStep({ goalId: 'goal-9', stepId: 'step-2', status: 'BLOCKED' }, directory); assert.equal((await readProgress(directory)).goals[0].status, 'BLOCKED'); await reorderProgressSteps('goal-9', ['step-2', 'step-1'], directory); assert.deepEqual((await readProgress(directory)).goals[0].steps.map(step => step.id), ['step-2', 'step-1']); await deleteProgressStep('goal-9', 'step-1', directory); assert.deepEqual((await readProgress(directory)).goals[0].steps.map(step => step.id), ['step-2']); });
test('step structure mutations reject duplicates, incomplete orders, last deletion, and stale revisions', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); const current = await readProgress(directory); await assert.rejects(() => addProgressStep('goal-9', { ...plan().steps[0] }, directory), /Duplicate/u); await assert.rejects(() => reorderProgressSteps('goal-9', [], directory), /exactly once/u); await assert.rejects(() => deleteProgressStep('goal-9', 'step-1', directory), /last step/u); await updateProgressGoal('goal-9', { title: 'Changed' }, directory); await assert.rejects(() => updateProgressGoal('goal-9', { title: 'Stale' }, directory, { expectedRevision: progressRevision(current) }), error => error.code === 'PROGRESS_REVISION_CONFLICT'); });
test('DONE is invalid without evidence in stored or newly added steps', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); const invalid = await readProgress(directory); invalid.goals[0].steps[0].status = 'DONE'; assert.match(validateProgress(invalid).join(' '), /requires evidence/u); await assert.rejects(() => addProgressStep('goal-9', { id: 'step-2', title: 'Done', status: 'DONE', acceptance: ['ok'], files: [], commands: [], evidence: [] }, directory), /DONE requires/u); });
test('progress next preserves plan order and separates blocked memory', async () => { const directory = root(); const steps = Array.from({ length: 5 }, (_, index) => ({ id: `step-${index + 1}`, title: `Step ${index + 1}`, acceptance: ['ok'], status: index === 0 ? 'TODO' : index === 1 ? 'BLOCKED' : index === 2 ? 'IN_PROGRESS' : 'TODO' })); await approvePlan({ goalId: 'goal-9', title: 'Many', validationEvidence: ['npm test'], steps, approved: true }, directory); const next = progressNext(await readProgress(directory), 'goal-9'); assert.deepEqual(next.next.map(step => step.stepId), ['step-1', 'step-3', 'step-4']); assert.deepEqual(next.blocked.map(step => step.stepId), ['step-2']); assert.equal(next.next[0].acceptance, undefined); });
test('progress next reports a completed goal without candidates', () => { const value = { schemaVersion: 1, goals: [{ id: 'goal-9', title: 'Done', status: 'DONE', executionMode: 'collaborative', steps: [{ id: 'step-1', title: 'Step', status: 'DONE', evidence: ['npm test'] }] }] }; assert.deepEqual(progressNext(value, 'goal-9').next, []); assert.equal(progressNext(value, 'goal-9').complete, true); });
test('progress next defaults goals without a mode to automatic', () => { const value = { goals: [{ id: 'goal-9', title: 'Legacy', status: 'ACTIVE', steps: [{ id: 'step-1', title: 'Step', status: 'TODO', evidence: [] }] }] }; assert.equal(progressNext(value, 'goal-9').mode, 'automatic'); });
test('progress next keeps stable order within one priority', () => { const steps = ['a', 'b', 'c', 'd'].map(id => ({ id, title: id, status: 'TODO', evidence: [] })); const value = { goals: [{ id: 'goal-9', steps }] }; assert.deepEqual(progressNext(value, 'goal-9').next.map(step => step.stepId), ['a', 'b', 'c']); });
test('progress next rejects an unknown goal', () => { assert.throws(() => progressNext({ goals: [] }, 'missing'), /Unknown goal/u); });
test('collaborative handoff detection requires every bounded next step and recognizes the autonomous offer', () => {
  const steps = [{ stepId: 'step-1', title: 'Define contract' }, { stepId: 'step-2', title: 'Verify transport' }];
  assert.equal(hasNextStepHandoff('Next: step-1 only', steps), false);
  assert.equal(hasNextStepHandoff('Next: Define contract, then step-2.', steps), true);
  assert.equal(hasAutonomousOffer('Je peux passer ce goal en mode automatique.'), true);
  assert.equal(hasAutonomousOffer('Voici les prochaines étapes.'), false);
  assert.equal(isExternallyBlocked({ steps: [{ status: 'BLOCKED' }, { status: 'BLOCKED' }, { status: 'BLOCKED' }, { status: 'TODO' }] }), false);
  assert.equal(isExternallyBlocked({ steps: [{ status: 'DONE' }, { status: 'BLOCKED', evidence: ['external: vendor unavailable'] }] }), true);
  assert.equal(isExternallyBlocked({ steps: [{ status: 'BLOCKED', evidence: ['waiting for approval'] }] }), false);
  assert.equal(isFullyBlocked({ steps: [{ status: 'DONE' }, { status: 'BLOCKED', evidence: [] }] }), true);
});
test('autonomous offer detection accepts the English agent wording', () => {
  assert.equal(hasAutonomousOffer('I can switch this goal to autonomous mode.'), true);
});
test('autonomous offer detection rejects unrelated automation wording', () => {
  assert.equal(hasAutonomousOffer('The test suite runs automatically.'), false);
});
test('next-step handoff detection rejects an empty final response', () => {
  assert.equal(hasNextStepHandoff('', [{ stepId: 'step-1', title: 'Verify' }]), false);
});
test('next-step handoff detection accepts a step identifier', () => {
  assert.equal(hasNextStepHandoff('Next: step-1', [{ stepId: 'step-1', title: 'Verify' }]), true);
});
test('external blocking requires at least one unfinished step', () => {
  assert.equal(isExternallyBlocked({ steps: [{ status: 'DONE' }] }), false);
});
test('external blocking rejects a mixed blocked and active goal', () => {
  assert.equal(isExternallyBlocked({ steps: [{ status: 'BLOCKED' }, { status: 'IN_PROGRESS' }] }), false);
});

test('goal selection prioritizes runnable work over stale blocked goals', () => {
  const blocked = { id: 'blocked', status: 'BLOCKED', steps: [{ status: 'BLOCKED', evidence: [] }] };
  const runnable = { id: 'runnable', status: 'ACTIVE', steps: [{ status: 'TODO', evidence: [] }] };
  assert.equal(selectProgressGoal({ goals: [blocked, runnable] }).id, 'runnable');
});

function execute(command, args, cwd) { return new Promise((resolve, reject) => { execFile(command, args, { cwd }, (error, stdout) => error ? reject(error) : resolve(stdout)); }); }
