import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emptyProgress, readProgress, validateProgress, validatePlan, approvePlan, progressStatus, progressNext, updateProgressStep, setProgressMode, renderProgress } from '../scripts/progress-core.mjs';

const plan = (overrides = {}) => ({ goalId: 'goal-9', title: 'Checklist', validationEvidence: ['tests/progress-core.test.mjs'], steps: [{ id: 'step-1', title: 'Define contract', acceptance: ['Schema validated'], files: ['.project/progress.json'], commands: ['npm test'], evidence: [] }], ...overrides });
const root = () => mkdtempSync(join(tmpdir(), 'progress-'));
const repositoryRoot = fileURLToPath(new URL('..', import.meta.url));

test('empty checklist is read-only and has stable shape', async () => { const directory = root(); assert.deepEqual(await readProgress(directory), emptyProgress()); assert.equal(existsSync(join(directory, '.project/progress.json')), false); });
test('published template starts without maintainer progress or tracked plan artifacts', async () => {
  const progress = await readProgress(repositoryRoot);
  assert.deepEqual(progress, emptyProgress());
  assert.equal(readFileSync(join(repositoryRoot, 'docs/progress.md'), 'utf8'), renderProgress(progress));
  assert.deepEqual(readdirSync(join(repositoryRoot, '.project')).filter(name => /-plan\.json$/u.test(name)), []);
});
test('validate-plan is read-only and rejects missing acceptance, files, commands, evidence', async () => { const directory = root(); const result = validatePlan({ goalId: 'goal-9', title: 'Bad', steps: [{ id: 'step-1', title: 'Bad' }] }, await readProgress(directory)); assert.equal(result.ok, false); assert.equal(existsSync(join(directory, '.project/progress.json')), false); assert.ok(result.errors.length >= 4); });
test('approval writes JSON and generated Markdown atomically and is idempotent', async () => { const directory = root(); const first = await approvePlan({ ...plan(), approved: true }, directory); const json = readFileSync(join(directory, '.project/progress.json'), 'utf8'); const markdown = readFileSync(join(directory, 'docs/progress.md'), 'utf8'); assert.deepEqual(JSON.parse(json), first); assert.match(markdown, /Checklist — ACTIVE/u); const second = await approvePlan({ ...plan(), approved: true }, directory); assert.deepEqual(second, first); });
test('multiple goals preserve insertion order and status is compact', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await approvePlan({ ...plan({ goalId: 'goal-10', title: 'Second' }), approved: true }, directory); assert.deepEqual(progressStatus(await readProgress(directory)).map(item => item.id), ['goal-9', 'goal-10']); });
test('approval is explicit and rejects paths, secrets, duplicate steps, and limits', async () => { const directory = root(); await assert.rejects(() => approvePlan(plan(), directory), /approved must be true/u); assert.equal(validatePlan({ ...plan(), steps: [{ ...plan().steps[0], files: ['../secret'] }], validationEvidence: ['ok'] }).ok, false); assert.equal(validatePlan({ ...plan(), steps: [{ ...plan().steps[0], id: 'step-1' }, { ...plan().steps[0], id: 'step-1' }] }).ok, false); assert.equal(validatePlan({ ...plan(), validationEvidence: ['apiKey: hidden'] }).ok, false); });
test('invalid stored JSON is rejected', async () => { const directory = root(); const path = join(directory, '.project/progress.json'); mkdirSync(join(directory, '.project')); writeFileSync(path, '{invalid'); await assert.rejects(() => readProgress(directory), /Cannot read progress checklist/u); });
test('stored progress validation accepts both execution modes and rejects unknown modes', () => { const value = { schemaVersion: 1, goals: [{ id: 'goal-9', title: 'Modes', status: 'ACTIVE', executionMode: 'autonomous', modeOffered: true, steps: [{ id: 'step-1', title: 'Verify', status: 'TODO', acceptance: ['ok'], files: ['.project/progress.json'], commands: ['npm test'], evidence: [] }] }] }; assert.deepEqual(validateProgress(value), []); assert.match(validateProgress({ ...value, goals: [{ ...value.goals[0], executionMode: 'manual' }] })[0], /executionMode/u); });
test('legacy goals migrate implicitly to collaborative mode', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); const value = await readProgress(directory); delete value.goals[0].executionMode; delete value.goals[0].modeOffered; writeFileSync(join(directory, '.project/progress.json'), JSON.stringify(value)); assert.equal(progressStatus(await readProgress(directory))[0].executionMode, 'collaborative'); });
test('mode requires explicit confirmation and can return to collaborative', async () => { const directory = root(); await approvePlan({ ...plan(), approved: true }, directory); await assert.rejects(() => setProgressMode('goal-9', 'autonomous', false, directory), /userConfirmed/u); await setProgressMode('goal-9', 'autonomous', true, directory); assert.equal((await readProgress(directory)).goals[0].executionMode, 'autonomous'); await setProgressMode('goal-9', 'collaborative', false, directory); assert.equal((await readProgress(directory)).goals[0].executionMode, 'collaborative'); });
test('step updates are bounded, idempotent, and recalculate goal status', async () => { const directory = root(); const two = { ...plan(), steps: [{ ...plan().steps[0], id: 'step-1' }, { ...plan().steps[0], id: 'step-2', title: 'Verify' }] }; await approvePlan({ ...two, approved: true }, directory); await assert.rejects(() => updateProgressStep({ goalId: 'goal-9', stepId: 'step-1', status: 'DONE' }, directory), /evidence/u); const update = { goalId: 'goal-9', stepId: 'step-1', status: 'DONE', evidence: ['npm test'] }; await updateProgressStep(update, directory); await updateProgressStep(update, directory); assert.equal((await readProgress(directory)).goals[0].status, 'ACTIVE'); await updateProgressStep({ goalId: 'goal-9', stepId: 'step-2', status: 'BLOCKED' }, directory); assert.equal((await readProgress(directory)).goals[0].status, 'BLOCKED'); });
test('progress next prioritizes active, blocked, then todo and limits three', async () => { const directory = root(); const steps = Array.from({ length: 5 }, (_, index) => ({ id: `step-${index + 1}`, title: `Step ${index + 1}`, acceptance: ['ok'], files: ['.project/progress.json'], commands: ['npm test'], status: index === 0 ? 'TODO' : index === 1 ? 'BLOCKED' : index === 2 ? 'IN_PROGRESS' : 'TODO' })); await approvePlan({ goalId: 'goal-9', title: 'Many', validationEvidence: ['npm test'], steps, approved: true }, directory); const next = progressNext(await readProgress(directory), 'goal-9'); assert.deepEqual(next.next.map(step => step.stepId), ['step-3', 'step-2', 'step-1']); });
